export const GROUP_ARTISTS = new Set([
  "blackpink", "glee cast", "bts", "jovem dionisio", "fifth harmony",
  "little mix", "rbd", "anavitória", "red velvet", "twice",
  "chloe x halle", "the neighbourhood", "los hermanos", "legião urbana",
  "erreway", "rouge", "one direction", "novos baianos", "newjeans",
  "i-dle", "fresno", "*nsync", "nsync", "calcinha preta",
  "companhia do calypso", "5 seconds of summer", "tribalistas",
  "cast of rent", "destiny's child", "rebeldes", "the beatles", "coldplay",
  "selena gomez & the scene", "girls generation", "snsd", "소녀시대",
  "spice girls", "the aces", "secos & molhados", "flo", "seafret",
  "dnce", "the pussycat dolls", "katseye", "tlc",
  "sandy & junior", "imagine dragons", "banda calypso",
  "artic monkeys", "arctic monkeys", "fleetwood mac", "chiquititas",
  "tears for fears", "radiohead", "f(x)", "wonder girls", "lagum",
  "rebelde la serie", "loona", "bonde do forró", "charlie brown jr",
  "black eyed peas", "girls aloud", "john lennon & yoko ono",
  "glass animals", "banda magníficos", "prettymuch", "jorge & mateus",
  "major lazer", "paramore", "five", "skank", "gorillaz", "haim",
  "no doubt", "exo", "as frenéticas", "banda ravelly",
  "florence + the machine", "trio esperança", "kid abelha",
  "twenty one pilots", "jonas brothers", "baiana system", "evanescence",
  "bigbang", "macklemore & ryan lewis", "momoland", "k/da", "css",
  "cansei de ser sexy", "mc loma e as gêmeas lacração", "teen angels",
  "forrozão tropykalia", "red hot chili peppers", "cavaleiros do forró",
  "jota quest", "exid", "francisco, el hombre",
  "the white stripes", "the black keys", "arcade fire",
  "toto", "journey", "bon jovi", "scorpions", "def leppard",
  "ac/dc", "guns n' roses", "aerosmith", "led zeppelin", "pink floyd",
  "the rolling stones", "the who", "queen", "deep purple", "black sabbath",
  "the police", "the cranberries", "garbage", "savage garden",
  "en vogue", "the jackson 5", "the temptations", "the supremes",
  "the bangles", "the go-gos", "talking heads", "blondie", "depeche mode",
  "new order", "joy division", "duran duran", "the cure",
  "pet shop boys", "erasure", "oingo boingo",
  "soda stereo", "charly garcia", "patricio rey", "los redonditos",
  "enanitos verdes", "divididos", "vilma palma e eus queros",
  "kapanga", "caifanes", "cafe tacvba", "molotov",
  "titãs", "charlie brown jr", "legião urbana", "jota quest",
  "skank", "armandinho", "os barões da pisadinha", "os hawaianos",
  "trio parada dura", "double you", "psirico",
  "sandy & junior", "jorge & mateus", "henrique & juliano",
  "simone & simaria", "maisi & ana",
  "twenty one pilots", "fall out boy", "panic! at the disco",
  "my chemical romance", "blink-182", "green day", "the killers",
  "foo fighters", "red hot chili peppers", "linkin park",
  "system of a down", "slipknot", "korn", "disturbed",
  "metallica", "iron maiden", "uranium", "poison", "mötley crüe",
  "backstreet boys", "westlife", "boyzone", "take that",
  "the wanted", "one direction", "five",
  "linkin park", "2ne1", "kid abelha",
  "the rolling stones", "fun.", "aespa", "ace of base",
  "rosa neon", "os paralamas do sucesso", "a great big world",
  "cnco", "everglow", "massive attack", "tegan and sara",
  "the strokes", "tuyo", "malta", "the chainsmokers", "abba",
  "city girls", "foo fighters", "one republic", "tame impala",
  "duran duran", "terno rei", "barão vermelho", "queen",
  "cpm 22", "the chicks", "oficina g3", "rbl",
  "wicked movie cast", "cage the elephant", "g.r.l.", "rpm",
  "silk city", "zé neto & cristiano", "lady antebellum",
  "girls' generation", "gfriend", "marian hill",
  "neiked", "gugudan", "terror jr", "seventeen", "i.o.i", "ravena", "turma do carrossel",
]);
