export const MALE_ARTISTS = new Set([
  "jão", "the weeknd", "pabllo vittar", "bad bunny", "harry styles",
  "post malone", "conan gray", "morgan wallen", "kanye west",
  "michael jackson", "steve lacy", "lil nas x", "adam lambert",
  "potyguara bardo", "bruno mars", "justin bieber", "zayn", "don l",
  "calvin harris", "shawn mendes", "aminé", "ed sheeran",
  "justin timberlake", "omar apollo", "lil peep", "troye sivan",
  "cazuza", "j balvin", "guilherme arantes", "drake", "silva",
  "roberto carlos", "gustavo mioto", "khalid", "fbc", "frank ocean",
  "charlie puth", "pedro sampaio", "billy joel", "bazzi", "bizarrap",
  "bk", "alceu valença", "luan santana", "orville peck",
  "benson boone", "criolo", "kendrick lamar", "david guetta",
  "tiago iorc", "joji", "gotye", "the kid laroi", "johnny hooker",
  "guitarricadelafuente", "jack harlow", "dadá boladão", "mark ronson",
  "elton john", "giveon", "bruce springsteen", "belchior", "yungblud",
  "niall horan", "grandson", "raul seixas", "lauv", "zedd", "dennis",
  "john mayer", "yung beef", "la cruz", "george michael", "mac miller",
  "victor kley", "ney matogrosso", "erasmo carlos", "dj snake", "mgk",
  "black alien", "cashmere cat", "eslabon armado", "enrique iglesias",
  "seu jorge", "tyler, the creator", "pharrell williams", "käärijä",
  "lucas pretti", "c. tangana", "padre fábio de melo", "roddy rich",
  "sombr", "eminem", "frejat", "lulu santos", "seungri",
  "luis miguel", "luis fonsi", "sebastian yatra", "camilo", "feid",
  "rauw alejandro", "myke towers", "wisin", "don omar", "nicky jam",
  "ozuna", "maluma", "daddy yankee", "arcángel", "natti natasha",
  "charly garcia", "soda stereo", "spinetta", "enanitos verdes",
  "divididos", "vilma palma", "kapanga", "andres calamaro",
  "gustavo cerati", "jorge ben jor", "snoop dogg", "eminem", "jay-z",
  "lil wayne", "travis scott", "travi$ scott", "future", "lil baby", "lil durk",
  "21 savage", "playboi carti", "lil uzi vert", "gunna",
  "kodak black", "roddy ricch", "baby keem", "denzel curry",
  "joyner lucas", "logic", "j. cole", "big sean", "meek mill",
  "wiz khalifa", "chance the rapper", "nas", "pusha t", "rick ross",
  "ludacris", "nelly", "dr. dre", "ice cube",
  "john legend", "maxwell", "d'angelo", "usher", "ne-yo",
  "chris brown", "chris borwn", "miguel", "bobby brown", "teddy riley", "babyface",
  "frank ocean", "daniel caesar", "giveon", "lucky daye",
  "burna boy", "wizkid", "davido", "rema", "fireboy dml",
  "central cee", "dave", "stormzy", "headie one", "aj tracey",
  "diplo", "martin garrix", "marshmello",
  "khalid", "brent faiyaz", "bryson tiller", "dominic fike",
  "troye sivan", "conan gray", "lauv", "reyne",
  "zezé di camargo",
  "chitaozinho", "armandinho", "marcelo d2",
  "luan santana", "joao gomes", "gabriel valim",
  "beck", "billy ray cyrus", "chico buarque", "kygo",
  "djavan", "rico dalasam", "tom aspaul", "jason derulo",
  "jorge drexler", "juice wrld", "role model", "lewis capaldi",
  "joão gomes", "jung kook", "labrinth", "trevor daniel",
  "emicida", "dj khaled", "ruel", "zeca baleiro",
  "chico césar", "sean paul", "andrew lloyd webber", "benny blanco",
  "jon batiste", "kafé", "nando reis", "niack", "tim maia",
  "jorge vercillo", "lost frequencies", "alfie templeman",
  "caetano veloso", "dorgival dantas", "jason mraz",
  "gilberto gil", "jackson wang", "projota", "emilio",
  "childish gambino", "safety trance", "tiësto", "timbaland",
  "vetromn", "di ferrero", "pk", "stephen sanchez", "aretuza lovi",
  "declan mckenna",
  "gloria groove",
  "sam smith", "james arthur", "steve aoki", "louis tomlinson",
  "brandon arreaga", "ty dolla $ign",
  "davi sabbag",
]);
