import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About — daegon charts" },
      { name: "description", content: "How daegon charts works, how each chart is calculated, and how data is audited." },
    ],
  }),
  component: AboutPage,
});

const fadeIn = { initial: { opacity: 0, y: 16 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.4 } };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <motion.section {...fadeIn} className="mb-12">
      <h2 className="section-banner"><span>{title}</span></h2>
      <div className="text-sm leading-relaxed text-[var(--muted-foreground)] space-y-3">{children}</div>
    </motion.section>
  );
}

function ChartCard({ name, formula, detail }: { name: string; formula: string; detail?: string }) {
  return (
    <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4 mb-3">
      <div className="font-bold text-[var(--foreground)] text-base mb-1">{name}</div>
      <div className="font-mono text-xs bg-[var(--muted)] text-[var(--accent)] px-3 py-2 rounded-lg inline-block mb-2">{formula}</div>
      {detail && <div className="text-xs text-[var(--muted-foreground)] leading-relaxed">{detail}</div>}
    </div>
  );
}

function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 md:py-16">
      <motion.div {...fadeIn} className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-black text-[var(--foreground)] tracking-tight mb-3">About Daegon Charts</h1>
        <p className="text-[var(--muted-foreground)] text-sm md:text-base max-w-xl mx-auto">
          Independent weekly music charts powered by publicly available data. No label influence, no editorial bias — just numbers.
        </p>
      </motion.div>

      <Section title="How It Works">
        <p>
          Every week, data is collected from public sources — primarily streaming platform counts, sales figures, and radio airplay metrics. This data is processed through weighted formulas to produce each chart ranking.
        </p>
        <p>
          All weekly charts are generated by Google Apps Script codes running directly in Google Sheets. Each chart has its own spreadsheet that is updated automatically via these scripts. The site reads from public Google Sheets links, which allows the data to be displayed here in real time.
        </p>
        <p>
          Charts are updated weekly and dated accordingly. Historical data is preserved so you can track how songs, albums, and artists perform over time.
        </p>
      </Section>

      <Section title="Auditing & Transparency">
        <p>
          All chart data is sourced from publicly available APIs and published reports. Streaming data comes directly from streaming platform APIs. Sales data is compiled from public sales reports. Radio airplay data is sourced from monitored station logs.
        </p>
        <p>
          Every chart entry links back to its source data where available. You can inspect individual song pages to see the exact streams, sales, and airplay numbers that determined each position. If you spot a discrepancy, every entry is auditable by design.
        </p>
      </Section>

      <Section title="Weekly Charts">
        <p>Each weekly chart uses a specific formula to rank entries. Here's how each one works:</p>

        <ChartCard
          name="Hot 100"
          formula="Sales (7d) × 3 + Streaming (28d) × 2 + Airplay × 1 = Points"
          detail="The flagship chart combining three pillars of music consumption into a single points-based ranking. Sales represent streaming platform plays from the current week multiplied by 1,000, weighted ×3 to reflect purchase intent. Streaming uses a rolling 4-week window of streaming platform plays multiplied by 1,000, weighted ×2 for sustained engagement. Airplay draws from the Top 40 Radio chart's audience metric, weighted ×1 for reach. Songs with 20 to 52 weeks on chart must reach Top 50 points to re-enter after dropping off. Songs with 52 or more weeks must reach Top 25 to re-enter. Songs with 20 or more weeks and no activity in any category are excluded."
        />

        <ChartCard
          name="Artist 50"
          formula="Sales (7d) + Streaming (28d) ÷ 2 = Units"
          detail="Ranks artists by total consumption units across all their songs. Sales are the total streaming platform plays across all songs in the current week, multiplied by 1,000. Streaming is the total streaming platform plays across all songs over 28 days, multiplied by 1,000, then divided by 2. The 7-day window counts fully while the 28-day window is halved to balance recency with staying power. Artists are ranked by total units."
        />

        <ChartCard
          name="Top 100 Albums"
          formula="Sales (7d) + Streaming (28d) ÷ 2 = Units"
          detail="Albums ranked by consumption units with a pre-release bonus system. Sales are streaming platform plays from the current week multiplied by 1,000. Streaming is streaming platform plays over 28 days multiplied by 1,000, divided by 2. Any plays before the official release date from singles are added to the debut week as pre-sales. Singles are excluded, only album tracks count. Album edition variants like Deluxe and Expanded are cleaned and merged into a single entry."
        />

        <ChartCard
          name="Digital Songs Sales"
          formula="Sales (7d) × 1,000"
          detail="Sales chart based solely on streaming platform plays from the current week, multiplied by 1,000. Uses a rolling 4-week window of plays for the ranking. Top 50 entries. Songs that drop off the chart must re-enter within the Top 25 to return. Songs with 20 or more weeks on chart must stay in the Top 50 to remain."
        />

        <ChartCard
          name="Streaming Songs"
          formula="Streaming (rolling 4 weeks) × 1,000"
          detail="Streaming chart ranked by a rolling 4-week window of streaming platform plays, multiplied by 1,000. Top 50 entries. Re-entries must reach the Top 25 to return to the chart after dropping off."
        />

        <ChartCard
          name="Top Albums Sales"
          formula="Sales (7d) × 1,000"
          detail="Sales-only album chart based on streaming platform plays from the current week, multiplied by 1,000. Top 50 entries. Any plays before the official release date from singles are added to the debut week as pre-sales. Singles are excluded, only album tracks count. Album edition variants like Deluxe and Expanded are cleaned and merged into a single entry."
        />

        <ChartCard
          name="Top Streaming Albums"
          formula="Streaming (28d) × 1,000"
          detail="Streaming-only album chart ranked by streaming platform plays over the last 28 days, multiplied by 1,000. Top 50 entries. Pre-release plays from singles are added to the total on the debut week but do not affect the weekly ranking. Singles are excluded, only album tracks count. Album edition variants are cleaned and merged into a single entry."
        />

        <ChartCard
          name="Radio Songs"
          formula="(Previous Audience × 0.90) + (Weekly Spins × 10) = Audience [cap: 100,000]"
          detail="Based on radio airplay spin data. Each week, 25% of accumulated spins are consumed as that week's spins. Each spin generates 10 audience points. Audience decays 10% weekly to reflect fading impact. A ceiling of 100,000 prevents songs from dominating indefinitely — once reached, the song stays capped until its weekly gain drops below 30,000, at which point it begins to decay naturally. Songs are ranked by accumulated audience. Max 3 songs per artist; a 4th entry is blocked if the artist already has 3 songs above 50,000 audience."
        />
      </Section>

      <Section title="Year-End Charts (YEC)">
        <p>
          Year-End charts are cumulative rankings that cover an entire calendar year. They aggregate all weekly positions throughout the year to determine the most successful songs, albums, and artists of that year. A song that stayed in the top 10 for most of the year will rank higher than a one-week #1 that disappeared shortly after.
        </p>
      </Section>

      <Section title="Greatest of All Time (GOAT)">
        <p>
          The GOAT charts rank the all-time biggest hits across the entire history of the chart. They use cumulative performance data across all available weeks to determine which songs, albums, and artists have had the greatest overall impact. These lists update as new data comes in and the chart's history grows.
        </p>
      </Section>

      <Section title="Stats">
        <p>
          The Stats section provides deeper analytics — total weeks at #1, career statistics for artists, cumulative streaming and sales milestones, and historical records. It's the place to explore the numbers behind the rankings.
        </p>
      </Section>

      <Section title="Certifications">
        <p>
          Certifications are awarded based on cumulative units sold/streams. Daegon Charts uses two separate certification systems depending on the format:
        </p>

        <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4 mb-3">
          <div className="font-bold text-[var(--foreground)] text-base mb-3">Songs — UK Style</div>
          <div className="space-y-2">
            {[
              { level: "Silver", units: "200,000" },
              { level: "Gold", units: "400,000" },
              { level: "Platinum", units: "600,000" },
              { level: "2× Platinum", units: "1,200,000" },
              { level: "3× Platinum", units: "1,800,000" },
              { level: "4× Platinum", units: "2,400,000" },
              { level: "5× Platinum", units: "3,000,000" },
              { level: "6× Platinum", units: "3,600,000" },
              { level: "7× Platinum", units: "4,200,000" },
              { level: "8× Platinum", units: "4,800,000" },
              { level: "9× Platinum", units: "5,400,000" },
              { level: "Diamond", units: "6,000,000" },
              { level: "2× Diamond", units: "12,000,000" },
            ].map((cert) => (
              <div key={cert.level} className="flex items-center justify-between text-xs">
                <span className="font-semibold text-[var(--foreground)]">{cert.level}</span>
                <span className="text-[var(--muted-foreground)]">{cert.units} units</span>
              </div>
            ))}
          </div>
          <div className="text-xs text-[var(--muted-foreground)] mt-3 leading-relaxed">
            Based on cumulative total units (sales + streaming equivalent units). Platinum increments by 600,000 per level after Platinum.
          </div>
        </div>

        <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
          <div className="font-bold text-[var(--foreground)] text-base mb-3">Albums — USA Style</div>
          <div className="space-y-2">
            {[
              { level: "Gold", units: "500,000" },
              { level: "Platinum", units: "1,000,000" },
              { level: "2× Platinum", units: "2,000,000" },
              { level: "3× Platinum", units: "3,000,000" },
              { level: "4× Platinum", units: "4,000,000" },
              { level: "5× Platinum", units: "5,000,000" },
              { level: "6× Platinum", units: "6,000,000" },
              { level: "7× Platinum", units: "7,000,000" },
              { level: "8× Platinum", units: "8,000,000" },
              { level: "9× Platinum", units: "9,000,000" },
              { level: "Diamond", units: "10,000,000" },
              { level: "2× Diamond", units: "20,000,000" },
            ].map((cert) => (
              <div key={cert.level} className="flex items-center justify-between text-xs">
                <span className="font-semibold text-[var(--foreground)]">{cert.level}</span>
                <span className="text-[var(--muted-foreground)]">{cert.units} units</span>
              </div>
            ))}
          </div>
          <div className="text-xs text-[var(--muted-foreground)] mt-3 leading-relaxed">
            Based on cumulative equivalent album units (sales + streaming equivalent units). Platinum increments by 1,000,000 per level after Platinum.
          </div>
        </div>
      </Section>

      <Section title="Chart Beat">
        <p>
          Chart Beat is an editorial section that highlights notable movements, milestones, and stories from the current week's charts. Think of it as the "news" layer on top of the raw data — debut analysis, record-breaking runs, and trend observations.
        </p>
      </Section>

      <Section title="Credits">
        <p>
          Daegon Charts is built and maintained independently. Here are the tools and services that make it possible:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-4">
          <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
            <div className="font-bold text-[var(--foreground)] text-sm">Google Apps Script</div>
            <div className="text-xs text-[var(--muted-foreground)] mt-1">All chart generation scripts run directly in Google Sheets via Apps Script, processing raw data into ranked charts automatically.</div>
          </div>
          <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
            <div className="font-bold text-[var(--foreground)] text-sm">Last.fm</div>
            <div className="text-xs text-[var(--muted-foreground)] mt-1">Radio airplay spin data is sourced from Last.fm's scrobble tracking system, providing the raw listening data behind the Radio Songs chart.</div>
          </div>
          <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
            <div className="font-bold text-[var(--foreground)] text-sm">VS Code</div>
            <div className="text-xs text-[var(--muted-foreground)] mt-1">The frontend application was developed in Visual Studio Code.</div>
          </div>
          <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
            <div className="font-bold text-[var(--foreground)] text-sm">Vercel</div>
            <div className="text-xs text-[var(--muted-foreground)] mt-1">Hosting and deployment infrastructure, ensuring fast and reliable access worldwide.</div>
          </div>
          <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
            <div className="font-bold text-[var(--foreground)] text-sm">GitHub</div>
            <div className="text-xs text-[var(--muted-foreground)] mt-1">Source code version control and collaboration platform.</div>
          </div>
          <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
            <div className="font-bold text-[var(--foreground)] text-sm">Spotify API</div>
            <div className="text-xs text-[var(--muted-foreground)] mt-1">Album artwork, artist images, and streaming data sourced directly from Spotify's public API.</div>
          </div>
        </div>
      </Section>

      <Section title="About Me">
        <div className="flex flex-col sm:flex-row items-center sm:items-start gap-6">
          <div className="shrink-0">
            <img
              src="/profile.jpg"
              alt="Daegon"
              className="w-32 h-32 rounded-full border-4 border-[#FF6D00] object-cover"
            />
          </div>
          <div className="text-center sm:text-left">
            <div className="text-lg font-bold text-[var(--foreground)] mb-1">Daegon</div>
            <div className="text-sm text-[var(--muted-foreground)] mb-3">Full-Stack Developer · Front-End Focused</div>
            <div className="text-sm text-[var(--muted-foreground)] space-y-1.5">
              <p>Based in Brazil. Passionate about data visualization, music, and building tools that bring numbers to life.</p>
              <p>Daegon Charts is a personal project that combines my interest in music analytics with modern web development. All chart logic, data processing, and frontend are built from scratch.</p>
              <p>Open to collaborations, freelance work, and new challenges. If you'd like to get in touch, reach out through the links below.</p>
            </div>
            <div className="flex items-center justify-center sm:justify-start gap-4 mt-4">
              <a
                href="https://github.com/dantaswt"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm font-semibold text-[var(--foreground)] hover:text-[var(--accent)] transition-colors"
              >
                <i className="fab fa-github text-lg" />
                GitHub
              </a>
              <a
                href="https://x.com/daegoncharts"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm font-semibold text-[var(--foreground)] hover:text-[var(--accent)] transition-colors"
              >
                <i className="fab fa-x-twitter text-lg" />
                @daegoncharts
              </a>
            </div>
          </div>
        </div>
      </Section>

      <motion.section {...fadeIn} className="mt-16 text-center">
        <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-6 md:p-8">
          <div className="text-lg font-bold text-[var(--foreground)] mb-2">Questions or corrections?</div>
          <div className="text-sm text-[var(--muted-foreground)]">
            If you notice data inconsistencies or have questions about methodology, reach out via the links in the footer.
          </div>
        </div>
      </motion.section>
    </div>
  );
}
