/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NumberOnesRouteImport } from './routes/number-ones'
import { Route as ChartBattleRouteImport } from './routes/chart-battle'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YearEndIndexRouteImport } from './routes/year-end.index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as GoatIndexRouteImport } from './routes/goat.index'
import { Route as YearEndChartIdRouteImport } from './routes/year-end.$chartId'
import { Route as StatsCategoryRouteImport } from './routes/stats.$category'
import { Route as GoatChartIdRouteImport } from './routes/goat.$chartId'
import { Route as ChartChartIdRouteImport } from './routes/chart.$chartId'
import { Route as ChartBeatBlogRouteImport } from './routes/chart-beat.$blog'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'
import { Route as AlbumSlugRouteImport } from './routes/album.$slug'
import { Route as ChartChartIdIndexRouteImport } from './routes/chart.$chartId.index'
import { Route as ChartChartIdDateRouteImport } from './routes/chart.$chartId.$date'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberOnesRoute = NumberOnesRouteImport.update({
  id: '/number-ones',
  path: '/number-ones',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartBattleRoute = ChartBattleRouteImport.update({
  id: '/chart-battle',
  path: '/chart-battle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearEndIndexRoute = YearEndIndexRouteImport.update({
  id: '/year-end/',
  path: '/year-end/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoatIndexRoute = GoatIndexRouteImport.update({
  id: '/goat/',
  path: '/goat/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearEndChartIdRoute = YearEndChartIdRouteImport.update({
  id: '/year-end/$chartId',
  path: '/year-end/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsCategoryRoute = StatsCategoryRouteImport.update({
  id: '/stats/$category',
  path: '/stats/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const GoatChartIdRoute = GoatChartIdRouteImport.update({
  id: '/goat/$chartId',
  path: '/goat/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartChartIdRoute = ChartChartIdRouteImport.update({
  id: '/chart/$chartId',
  path: '/chart/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartBeatBlogRoute = ChartBeatBlogRouteImport.update({
  id: '/chart-beat/$blog',
  path: '/chart-beat/$blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumSlugRoute = AlbumSlugRouteImport.update({
  id: '/album/$slug',
  path: '/album/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartChartIdIndexRoute = ChartChartIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChartChartIdRoute,
} as any)
const ChartChartIdDateRoute = ChartChartIdDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => ChartChartIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/chart-battle': typeof ChartBattleRoute
  '/number-ones': typeof NumberOnesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/chart-beat/$blog': typeof ChartBeatBlogRoute
  '/chart/$chartId': typeof ChartChartIdRouteWithChildren
  '/goat/$chartId': typeof GoatChartIdRoute
  '/stats/$category': typeof StatsCategoryRoute
  '/year-end/$chartId': typeof YearEndChartIdRoute
  '/goat/': typeof GoatIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/year-end/': typeof YearEndIndexRoute
  '/chart/$chartId/$date': typeof ChartChartIdDateRoute
  '/chart/$chartId/': typeof ChartChartIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/chart-battle': typeof ChartBattleRoute
  '/number-ones': typeof NumberOnesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/chart-beat/$blog': typeof ChartBeatBlogRoute
  '/goat/$chartId': typeof GoatChartIdRoute
  '/stats/$category': typeof StatsCategoryRoute
  '/year-end/$chartId': typeof YearEndChartIdRoute
  '/goat': typeof GoatIndexRoute
  '/stats': typeof StatsIndexRoute
  '/year-end': typeof YearEndIndexRoute
  '/chart/$chartId/$date': typeof ChartChartIdDateRoute
  '/chart/$chartId': typeof ChartChartIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/chart-battle': typeof ChartBattleRoute
  '/number-ones': typeof NumberOnesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/chart-beat/$blog': typeof ChartBeatBlogRoute
  '/chart/$chartId': typeof ChartChartIdRouteWithChildren
  '/goat/$chartId': typeof GoatChartIdRoute
  '/stats/$category': typeof StatsCategoryRoute
  '/year-end/$chartId': typeof YearEndChartIdRoute
  '/goat/': typeof GoatIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/year-end/': typeof YearEndIndexRoute
  '/chart/$chartId/$date': typeof ChartChartIdDateRoute
  '/chart/$chartId/': typeof ChartChartIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/chart-battle'
    | '/number-ones'
    | '/sitemap.xml'
    | '/album/$slug'
    | '/artist/$slug'
    | '/chart-beat/$blog'
    | '/chart/$chartId'
    | '/goat/$chartId'
    | '/stats/$category'
    | '/year-end/$chartId'
    | '/goat/'
    | '/stats/'
    | '/year-end/'
    | '/chart/$chartId/$date'
    | '/chart/$chartId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/chart-battle'
    | '/number-ones'
    | '/sitemap.xml'
    | '/album/$slug'
    | '/artist/$slug'
    | '/chart-beat/$blog'
    | '/goat/$chartId'
    | '/stats/$category'
    | '/year-end/$chartId'
    | '/goat'
    | '/stats'
    | '/year-end'
    | '/chart/$chartId/$date'
    | '/chart/$chartId'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/chart-battle'
    | '/number-ones'
    | '/sitemap.xml'
    | '/album/$slug'
    | '/artist/$slug'
    | '/chart-beat/$blog'
    | '/chart/$chartId'
    | '/goat/$chartId'
    | '/stats/$category'
    | '/year-end/$chartId'
    | '/goat/'
    | '/stats/'
    | '/year-end/'
    | '/chart/$chartId/$date'
    | '/chart/$chartId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRoute
  ChartBattleRoute: typeof ChartBattleRoute
  NumberOnesRoute: typeof NumberOnesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AlbumSlugRoute: typeof AlbumSlugRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
  ChartBeatBlogRoute: typeof ChartBeatBlogRoute
  ChartChartIdRoute: typeof ChartChartIdRouteWithChildren
  GoatChartIdRoute: typeof GoatChartIdRoute
  StatsCategoryRoute: typeof StatsCategoryRoute
  YearEndChartIdRoute: typeof YearEndChartIdRoute
  GoatIndexRoute: typeof GoatIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  YearEndIndexRoute: typeof YearEndIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-ones': {
      id: '/number-ones'
      path: '/number-ones'
      fullPath: '/number-ones'
      preLoaderRoute: typeof NumberOnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-battle': {
      id: '/chart-battle'
      path: '/chart-battle'
      fullPath: '/chart-battle'
      preLoaderRoute: typeof ChartBattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year-end/': {
      id: '/year-end/'
      path: '/year-end'
      fullPath: '/year-end/'
      preLoaderRoute: typeof YearEndIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goat/': {
      id: '/goat/'
      path: '/goat'
      fullPath: '/goat/'
      preLoaderRoute: typeof GoatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year-end/$chartId': {
      id: '/year-end/$chartId'
      path: '/year-end/$chartId'
      fullPath: '/year-end/$chartId'
      preLoaderRoute: typeof YearEndChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$category': {
      id: '/stats/$category'
      path: '/stats/$category'
      fullPath: '/stats/$category'
      preLoaderRoute: typeof StatsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goat/$chartId': {
      id: '/goat/$chartId'
      path: '/goat/$chartId'
      fullPath: '/goat/$chartId'
      preLoaderRoute: typeof GoatChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart/$chartId': {
      id: '/chart/$chartId'
      path: '/chart/$chartId'
      fullPath: '/chart/$chartId'
      preLoaderRoute: typeof ChartChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-beat/$blog': {
      id: '/chart-beat/$blog'
      path: '/chart-beat/$blog'
      fullPath: '/chart-beat/$blog'
      preLoaderRoute: typeof ChartBeatBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$slug': {
      id: '/album/$slug'
      path: '/album/$slug'
      fullPath: '/album/$slug'
      preLoaderRoute: typeof AlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart/$chartId/': {
      id: '/chart/$chartId/'
      path: '/'
      fullPath: '/chart/$chartId/'
      preLoaderRoute: typeof ChartChartIdIndexRouteImport
      parentRoute: typeof ChartChartIdRoute
    }
    '/chart/$chartId/$date': {
      id: '/chart/$chartId/$date'
      path: '/$date'
      fullPath: '/chart/$chartId/$date'
      preLoaderRoute: typeof ChartChartIdDateRouteImport
      parentRoute: typeof ChartChartIdRoute
    }
  }
}

interface ChartChartIdRouteChildren {
  ChartChartIdDateRoute: typeof ChartChartIdDateRoute
  ChartChartIdIndexRoute: typeof ChartChartIdIndexRoute
}

const ChartChartIdRouteChildren: ChartChartIdRouteChildren = {
  ChartChartIdDateRoute: ChartChartIdDateRoute,
  ChartChartIdIndexRoute: ChartChartIdIndexRoute,
}

const ChartChartIdRouteWithChildren = ChartChartIdRoute._addFileChildren(
  ChartChartIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRoute,
  ChartBattleRoute: ChartBattleRoute,
  NumberOnesRoute: NumberOnesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AlbumSlugRoute: AlbumSlugRoute,
  ArtistSlugRoute: ArtistSlugRoute,
  ChartBeatBlogRoute: ChartBeatBlogRoute,
  ChartChartIdRoute: ChartChartIdRouteWithChildren,
  GoatChartIdRoute: GoatChartIdRoute,
  StatsCategoryRoute: StatsCategoryRoute,
  YearEndChartIdRoute: YearEndChartIdRoute,
  GoatIndexRoute: GoatIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  YearEndIndexRoute: YearEndIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
